version: '3.7'

services:
  web-app:
    build: ./webapp
    volumes:
      - webapp_build:/app/tw-webapp/dist
      
  apollo:
    build: ./apollo
    ports:
      - 4000:4000
    restart: always
  
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - webapp_build:/app
    ports:
      - 80:80
    depends_on:
      - web-app
      - apollo

      
volumes:
  webapp_build:
