version: '3.7'

services:
  django:
    build: ./django
    restart: always
    command: gunicorn SAIS_API.wsgi:application --bind 0.0.0.0:8000 --workers 4 --log-level=debug
    volumes:
      - ./app/:/app/
    expose:
      - 8000
    environment:
      - SECRET_KEY=secret_key
      - DJANGO_DEBUG=True
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=NGNvarvpZIpa8R88
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: NGNvarvpZIpa8R88
  
  pgadmin:
    restart: always  
    image: dpage/pgadmin4:latest
    links:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ca
      PGADMIN_DEFAULT_PASSWORD: Hl8q5XmFN2yV1VLU
      PGADMIN_LISTEN_PORT: 5555

  graphql-engine:
    image: hasura/graphql-engine:latest
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:NGNvarvpZIpa8R88@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: eDfGfj041tHBYkX9
  # web-app is a build slave

  web-app:
    build: ./webapp
    volumes:
      - webapp_build:/app/tw-webapp/dist
      
  apollo:
    build: ./apollo
    restart: always
  
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - webapp_build:/app
    ports:
      - 80:80
    depends_on:
      - web-app
      - apollo
      - graphql-engine

volumes:
  webapp_build:
  postgres_data:

