version: '3.7'
services:
  db:
    image: postgres:11.1-alpine
    restart: always
    ports:
	  - 5432:5432
	volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    restart: always
    image: dpage/pgadmin4:4.3
    links:
      - db
    ports:
      - 5555:5555
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5555
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - 8080:8080
    depends_on:
    - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  postgres_data: